name: "meow lint action"
description: "check"
inputs:
  github_token:
    required: true
    description: "GitHub token"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: check env
      shell: bash
      run: |
        type gh >/dev/null 2>&1 || echo "gh is required"

    - name: Run checker
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        files=()
      
        while IFS= read -r file; do
          [[ "$file" != *.md && "$file" != *.mdx ]] && continue
          files+=("$file")
        done < <(
          gh pr diff ${{ github.event.pull_request.number }} --name-only
        )
      
        if [ ${#files[@]} -eq 0 ]; then
          echo "No markdown files changed, skipping content lint."
          exit 0
        fi
      
        python ${{ github.action_path }}/src/content_lint.py -i "${files[@]}"
