# this workflow use as pull request check 

name: test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - uses: actions/checkout@v6

      # run lint
      - name: Run Meow Linter
        uses: Neko-vecter/meow-lint@main
        with:
          github_token: ${{ github.token }}
